### ISSUE TITLE
search page design

### ISSUE THREAD

**Issue by davelandry** [datamexico/datamexico-site#19]

**Comment by gabrielaperezponce** [comment]
Done and files delivered to Carlos for implementation

![explore-search-dmx-01](https://user-images.githubusercontent.com/5561308/66835099-4fa48d00-ef35-11e9-8388-3698a3ff3089.png)
![explore-search-dmx-02](https://user-images.githubusercontent.com/5561308/66835100-4fa48d00-ef35-11e9-8795-e68f82cd5cdd.png)
![explore-search-dmx-03](https://user-images.githubusercontent.com/5561308/66835102-4fa48d00-ef35-11e9-83f6-5dfbd2fd10c2.png)
