### ISSUE TITLE
Vizbuilder Improvements

### ISSUE THREAD

**Issue by azapatam** [datamexico/datamexico-site#203]
- [x] Notify the user that it is necessary to add a drilldown for the queries to work. (Maybe add an alert icon or disable the "Execute Query" button until a drilldown is selected).
- [ ] ~~Add a button to share the graphs produced (similar to the button that the visualizations have in the profiles).~~
- [x] Add a "pop-up" on Measures, Drilldowns and Cuts with the definition of each one.
- [x] Is it possible to hide the "Query Option" menu from the navigation bar?
- [x] The "pop-up" is not displayed when clicking the filter icon next to Measures in the navigation panel.
- [x] INEGI's foreign trade cube must appear in the list of available cubes
- [ ] Suggestion: Add a link to the data dictionary when selecting a data cube
- [x] Get quarter formatting working
- [ ] Coloring country maps (the map appears without coloring)
- [x] Remove green background in tooltips of countries

**Comment by greenrhyno** [comment]
Adding share buttons/links to the graphs in Vizbuilder will be pretty complicated and definitely won’t happen soon. Let me know how serious the client is about this request — I will discuss it with some of the eng team soon to figure out how much time and effort this will actually take.

I crossed it out above to show that this will be needed to be a separate issue.

**Comment by azapatam** [comment]
About the green background in the country tooltips, just check that it wasn't your changes that introduced the bug:
![image](https://user-images.githubusercontent.com/42551166/151567690-73f5948f-323e-4867-82be-822dec086a43.png)
