### ISSUE TITLE
Add a step-by-step guide on the Vizbuilder

### ISSUE THREAD

**Issue by azapatam** [datamexico/datamexico-site#232]
Add a step-by-step guide to generate a query in Vizbuilder instead of the cube that appears when the page is loaded for the first time
- [x]  @cgobantes Coordinate with Gaby or Tati (whoever has time) to generate a design of this and the narrative
- [x] @greenrhyno Implement the proposed design

**Comment by palamago** [comment]
I'm taking care of it

**Comment by palamago** [comment]
Design: https://www.figma.com/file/qQQa1mIAGvTx0YYBPIhVOd/Step-by-step-Guide-VizbuilderDMX?node-id=57%3A2
