### ISSUE TITLE
assorted UI/UX bugs

### ISSUE THREAD

**Issue by davelandry** [datamexico/datamexico-site#38]

**Comment by alexandersimoes** [comment]
- [ ] stats overlapping titles with long names
- [ ] occupation page titles are left aligned (https://dev.datamexico.org/es/profile/occupation/611)
- [ ] treemap font-size is not resize based on available size in rectangle

**Comment by perpetualgrimace** [comment]
@alexandersimoes regarding the occupation title alignment, there was a visualization in the occupation hero section with an incomplete configuration. So on the front end, the hero section template was adding a container for the visualization, and applying the styles necessary for a hero section with a visualization, but no visualization was rendering — thus the wonky alignment. 

I deleted the visualization and now it's displaying correctly.
