### ISSUE TITLE
create google sheet of HS product names to shorten names

### ISSUE THREAD

**Issue by alexandersimoes** [datamexico/datamexico-site#46]
Currently, there are many product names in spanish (and some in english too) with very long titles. Like the following: https://dev.datamexico.org/es/profile/product/178703

<img width="1177" alt="Screen Shot 2019-12-04 at 3 23 42 PM" src="https://user-images.githubusercontent.com/252276/70192503-e685fe00-16c9-11ea-9f9a-afcd338b84ca.png">

We should shorten these titles, but to get an idea of which ones are most problematic it would be good to have a google sheet with different sheets for 2 digit, 4 digit and 6 digit products including their names in english and spanish, total export amount and current name, so that we can all work on editing them.

**Comment by D2SD** [comment]
this is the url:
https://docs.google.com/spreadsheets/d/1glcGMmMkL2u91z5tjsJvTGVJYoAf3qOSWLiHz8_R3GM/edit?usp=sharing
