### ISSUE TITLE
infographic icon design

### ISSUE THREAD

**Issue by davelandry** [datamexico/datamexico-site#50]

**Comment by gabrielaperezponce** [comment]
![infographic-section](https://user-images.githubusercontent.com/5561308/71032171-90ff1780-20f3-11ea-9d36-b642633176f9.png)

@simoes or @davelandry  can you tell me if any of these drawings is not correct or clear in explaining the concept in a simple way.

**Comment by davelandry** [comment]
@gabrielaperezponce these are great! the only one that is confusing for me is "Census Gross Value Added". If I understand the term correctly, it refers to the value of a location's economic outputs subtracted by the value of their economic input.

**Comment by gabrielaperezponce** [comment]
Ok, I'm going to review the concept and prepare another icon there. 
Thanks for the feedback @davelandry

**Comment by gabrielaperezponce** [comment]
Ok, I made some adjustments, I don't know if this icon works well for that concept

![iconographic-production-datamexico](https://user-images.githubusercontent.com/5561308/71197481-769e7880-2270-11ea-9174-d643d5a752df.png)

the other thing in which I have doubt is whether it needs to be ideally a single icon or a more extended illustration like the one that appears here. 
<img width="1649" alt="Captura de Pantalla 2019-12-19 a la(s) 3 04 14 p  m" src="https://user-images.githubusercontent.com/5561308/71197644-dc8b0000-2270-11ea-9369-bbde6856c3de.png">

**Comment by davelandry** [comment]
New icons look great! 👍

@alexandersimoes knows more about the content usage, so he should be able to answer your question on whether he needs more extended illustrations.

**Comment by alexandersimoes** [comment]
@gabrielaperezponce it would be better to have individual icons for each category. Can you export those to PNGs and add them to a folder in the datamexico google drive?

**Comment by gabrielaperezponce** [comment]
@alexandersimoes In this folder I left the illustrations in png format https://drive.google.com/open?id=11OSKM7QThejsLBsT713bs_rOix36QNXr
