### ISSUE TITLE
education and connectivity infographic icons

### ISSUE THREAD

**Issue by davelandry** [datamexico/datamexico-site#56]

**Comment by gabrielaperezponce** [comment]
@alexandersimoes, @davelandry I prepared these illustrations. Let me know if you think there is something that does not represent the concept well. Thank you

![conectivity](https://user-images.githubusercontent.com/5561308/71990599-6eec4700-3212-11ea-8361-77a7d2fcf4e1.png)
![education](https://user-images.githubusercontent.com/5561308/71990601-6eec4700-3212-11ea-9328-e0df7609d7f1.png)

**Comment by alexandersimoes** [comment]
I think these look good! Please add them to the google drive datamexico folder and I will add @ffigueroal here to add these to the site. Thanks!

**Comment by gabrielaperezponce** [comment]
https://drive.google.com/open?id=17bZFa6BbeKsok2N509FEzzAFqM_30vds

https://drive.google.com/open?id=137daqgtmzHeRYt6EGt0pgre647C7lMrJ
