### ISSUE TITLE
clean up default d3plus visualization styles

### ISSUE THREAD

**Issue by davelandry** [datamexico/datamexico-site#9]

**Comment by gabrielaperezponce** [comment]
Here is a preview of the color palette and icons for some categories of visualizations  @cnavarreteliz 
[palette-color-datamex-parte1.pdf](https://github.com/datamexico/datamexico-site/files/3632882/palette-color-datamex-parte1.pdf)


![paleta-icons-dmx-01](https://user-images.githubusercontent.com/5561308/65275350-dd8a8500-dafb-11e9-9457-03e82103030b.png)
![paleta-icons-dmx-02](https://user-images.githubusercontent.com/5561308/65275351-de231b80-dafb-11e9-91d9-e749c3c32790.png)
![paleta-icons-dmx-03](https://user-images.githubusercontent.com/5561308/65275352-de231b80-dafb-11e9-8fa4-e5d92a32fa52.png)
![paleta-icons-dmx-04](https://user-images.githubusercontent.com/5561308/65275353-de231b80-dafb-11e9-83f4-ddbc4d1b8566.png)
![paleta-icons-dmx-05](https://user-images.githubusercontent.com/5561308/65275354-de231b80-dafb-11e9-8913-9d467b34d05a.png)

**Comment by alexandersimoes** [comment]
This is great, thanks @gabrielaperezponce!

I believe we will need the icons exported as individual png files. It would be great to have a white and black version both with transparent backgrounds. Similar to how we do the product icons on the OEC:

https://oec.world/static/img/icons/hs/hs_01.png
https://oec.world/static/img/icons/hs/hs_01_black.png

Also @cnavarreteliz do you have a naming convention you prefer for the icons?

**Comment by cnavarreteliz** [comment]
@alexandersimoes I would like to use a similar format (`slug_<id>.png`). Where do you have store the files @gabrielaperezponce ?
